export const IMAGE_UPLOAD = "IMAGE_UPLOAD"


export const manageAppActionTypes = {
     ADD_MAIN_CHAPTER  : "ADD_MAIN_CHAPTER",
     UPDATE_MAIN_CHAPTER  : "UPDATE_MAIN_CHAPTER",
     DELETE_MAIN_CHAPTER  : "DELETE_MAIN_CHAPTER",

     SET_ONE_MAIN_CHAPTER : "SET_ONE_MAIN_CHAPTER" , 
     HIDE_UPDATE_MAIN_CHAPTER : "HIDE_UPDATE_MAIN_CHAPTER"
}
